# Generated by Django 3.0.7 on 2020-06-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20200624_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction_type',
            field=models.CharField(choices=[('like', 'like'), ('heart', 'heart'), ('sad', 'sad'), ('haha', 'haha'), ('dislike', 'dislike')], max_length=10),
        ),
    ]
