# Generated by Django 3.0.7 on 2020-06-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20200624_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction_type',
            field=models.CharField(choices=[('like', 'like'), ('heart', 'heart'), ('sad', 'sad'), ('haha', 'haha'), ('angry', 'angry')], max_length=10),
        ),
    ]
